#quick way to get the muon sim to run

/vis/scene/create
/vis/open OGLIX 800x800-0+0
/vis/verbose errors
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointVector 1 -1 -1
/vis/viewer/set/viewpointVector 0 1 0

/run/initialize
/vis/drawVolume
/vis/viewer/flush

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 10 0 0 mm
/gps/pos/halfx 25 mm
/gps/pos/halfy 25 mm
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1

/gps/ene/type Mono
/gps/ene/mono 60 keV
/gps/direction -1 0 0
#/gps/number 10

#/gps/ene/type User
#/gps/hist/type energy
#/gps/hist/point 0 10.5
#/gps/hist/point 0.05 10.5
#/gps/hist/point 0.0501 0.5
#/gps/hist/point 1 0.5
#/gps/hist/point 1.01 0
#/gps/hist/inter Lin

#######################################
#/gps/position 10 0 9 cm
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/halfx 2 cm
#/gps/pos/halfy 0.5 cm
#/gps/pos/rot1 0 1 0
#/gps/pos/rot2 0 0 1
###################################3##

/vis/scene/endOfEventAction accumulate 1
/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set proton yellow
#/vis/modeling/trajectories/list
/vis/viewer/set/background white

/vis/viewer/flush
/run/beamOn 100


