#quick way to get the muon sim to run

/vis/scene/create
/vis/open OGLIX 800x800-0+0
/vis/verbose errors
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointVector 0 1 0

/run/initialize
/vis/drawVolume
/vis/viewer/flush

#/gps/position 900 0 177.3 cm   #Z position here is chosen by projecting 4th layer at 43.1deg angle
/gps/position 900 0 243 mm
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/halfx 0.1 cm
/gps/pos/halfy 0.1 cm

/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/direction -1 0 0
#######################################
#/gps/position 10 0 9 cm
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/halfx 2 cm
#/gps/pos/halfy 0.5 cm
#/gps/pos/rot1 0 1 0
#/gps/pos/rot2 0 0 1
#/gps/direction -1 0 0
###################################3##
/gps/particle mu-
/gps/ene/type Mono
/gps/ene/mono 4 GeV

/vis/scene/endOfEventAction accumulate 1
/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set proton yellow
#/vis/modeling/trajectories/list
/vis/viewer/set/background white

/vis/viewer/flush
/run/beamOn 1


