#quick way to get the muon sim to run

/vis/scene/create
/vis/open OGLIX 800x800-0+0
/vis/verbose errors
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointVector 0 1 0

/run/initialize
/vis/drawVolume
/vis/viewer/flush

/gps/position 100 0 0 mm
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/halfx 0.1 cm
/gps/pos/halfy 0.1 cm
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/ang/type user
/gps/hist/type theta

/gps/hist/point 0 1
/gps/hist/point .77 1
/gps/hist/point 1.57079632679489 1


#/gps/hist/file /media/ryan/Storage/computing/mqFullSim/macros/MuonAngDist.dat


#######################################
#/gps/position 10 0 9 cm
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/halfx 2 cm
#/gps/pos/halfy 0.5 cm
#/gps/pos/rot1 0 1 0
#/gps/pos/rot2 0 0 1
#/gps/direction -1 0 0
###################################3##
/gps/particle mu-
/gps/ene/type Mono
/gps/ene/mono 4 GeV

/vis/scene/endOfEventAction accumulate 1
/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set proton yellow
#/vis/modeling/trajectories/list
/vis/viewer/set/background white

/vis/viewer/flush
/run/beamOn 1
/gps/position -100 0 0 mm
/run/beamOn 1


