#quick way to get the muon sim to visualize

/vis/scene/create
/vis/open OGLIX 1600x1200-0+0
/vis/verbose errors
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointVector 1 -1 -1
/vis/viewer/set/viewpointVector 0 1 0

/run/initialize
/vis/drawVolume
/vis/viewer/flush


/vis/scene/endOfEventAction accumulate 1
/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set proton orange
/vis/modeling/trajectories/drawByParticleID-0/set monopole blue
/vis/viewer/set/background white

/vis/viewer/flush


