#quick way to get the muon sim to visualize

/vis/scene/create
/vis/open OGLSX 1600x1200-0+0
/vis/verbose errors
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointVector 1 -1 -1
/vis/viewer/set/viewpointVector 0 1 0



/run/initialize
/vis/drawVolume
/vis/viewer/set/background white
/vis/scene/add/eventID
/vis/viewer/zoomTo 3.5
/vis/viewer/flush

#        /vis/viewer/set/timeWindow/displayLightFront true 20 0 0 cm -0.01 ns
        # Then set a time window and save

#/vis/scene/endOfEventAction accumulate 1
#/tracking/storeTrajectory 1

/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/add/trajectories rich
/vis/modeling/trajectories/drawByParticleID-0/default/setTimeSliceInterval 0.01 ns
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set proton orange
/vis/modeling/trajectories/drawByParticleID-0/set monopole blue
/vis/ogl/set/displayListLimit 10000000
#/vis/viewer/set/background white
/vis/viewer/set/timeWindow/displayHeadTime true
#/vis/viewer/set/timeWindow/fadeFactor 1

        #/control/execute sidegamma_no_vis.mac
        /control/execute mcp_novis.mac
