#include "TCanvas.h"
#include "TTree.h"
#include "TGaxis.h"
#include "TStyle.h"
#include "TFile.h"
#include <iostream>
#include "TMath.h"
#include "TChain.h"
#include "/media/ryan/Storage/computing/mqFullSim/include/mqROOTEvent.hh"
#include "TGraph.h"
#include "TVector.h"
#include "TVectorF.h"
#include "TH1.h"
#include "TH1F.h"
#include "TString.h"
#include "TChain.h"
using namespace std;


void MuonTrigPECount(){

//retreive file

  TChain rootEvents("Events");
  TString fileDir = "/media/ryan/Storage/computing/mqFullSim/data/R97/muonTriggerCorrected/Close5p7/";
  TString xTitle = "Number of Muon-Generated Photons";
  rootEvents.Add(fileDir+"MilliQan.root");
  std::cout << "Reading file..." << std::endl;
  mqROOTEvent* myROOTEvent = new mqROOTEvent();
  rootEvents.SetBranchAddress("ROOTEvent", &myROOTEvent);
  Long64_t nentries=rootEvents.GetEntries();

//initialize variables
  double EDep=0;
  double h=4.135668*pow(10,-15);
  double c=3*pow(10,8);
  double wavelength;
  double final_z=0;
  double final_x=0;
  double final_y=0;
  double XYMag=0;
  int fiberInc=0;
  int under=0;
  int PECount=0;
  bool wls_conv  = false;
vector<double> wave;
int pmtCount=0;
int photonCount=0;
int numPhotons=0;
int numPhotonTracks=0;
int numPMTHits=0;
vector<int> muonHits;
bool trig = false;
int count = 0;
//get data in file
  for (Long64_t i=0;i<nentries;i++) {
	//my issue may have to do with this
	rootEvents.GetEntry(i);
		trig = myROOTEvent->GetMuonTrigger();
		if (trig){
			numPMTHits=myROOTEvent->GetPMTRHits()->size();
			muonHits.push_back(numPMTHits);
			count++;
			if(count%100==0) cout << "Finished analyzing event " << count << endl;
//			if (count==1000) break;
		}
   }


TFile *out = new TFile(fileDir+"MilliQanMuonPE.root","RECREATE");
TH1I* hmphotReal = new TH1I("hmphotReal","",200,0,20000);
for (int j=0; j<muonHits.size(); j++){
	if(muonHits[j]>0) hmphotReal->Fill(muonHits[j]);
}


hmphotReal->SetLineColor(kBlue);

hmphotReal->GetXaxis()->SetTitle(xTitle);
hmphotReal->GetYaxis()->SetTitle("Bin Members");
hmphotReal->SetTitle("Photons Directly Generated by Incident Muons");

TChain ch("Events");
   ch.Add("/media/ryan/Storage/computing/mqFullSim/data/R97/Close5p7/MilliQan.root");

  TH1F *hMEDep = new TH1F("hMECount","Photoelectrons Detected Per Incident Muon, Test",200,0,20000);
  hMECount->GetXaxis()->SetTitle("Number of Photoelectrons Detected");
  hMECount->GetYaxis()->SetTitle("Bin Members");

  TCanvas *c1 = new TCanvas("c1","c1",0,400,600,300);
  ch.Draw("NbOfPMTHits>>hMECount");
 
  hmphotReal->Draw("same");
  //hmphotReal->Draw();

muonHits.clear();

out->Write();
}
