#===============================================================================
# Geant4 macro file created by M. Hughes to simulate the LED source(s) embedded
# in the plexiglass sidewall of the EDELWEISS-II neutron counter.
#

###################################################
#Setting verbose level
#/control/verbose 0
/run/verbose 0
/tracking/verbose 1
#/optics_engine/selectOpProcess Cerenkov 
#/optics_engine/setOpProcessUse false

/run/initialize

###################################################
#Setting display settings
#/vis/open HepRepFile
#/vis/open OGLIX 600x600-0+0
#/vis/open OGL
#/vis/open DAWNFILE
/vis/open VRML2FILE
/vis/drawVolume
#/vis/viewer/set/viewpointThetaPhi 45 30 deg
#/vis/viewer/zoom 1

/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set gamma red
#/vis/modeling/trajectories/drawByParticleID-0/set neutron green
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
#/vis/modeling/trajectories/drawByParticleID-0/set proton black
#/vis/modeling/trajectories/list

/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
/vis/filtering/trajectories/attributeFilter-0/addInterval 2 GeV 4 GeV
/vis/filtering/trajectories/attributeFilter-0/addInterval 3 eV 3.1 eV



#/vis/filtering/trajectories/create/attributeFilter
#/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
#/vis/filtering/trajectories/attributeFilter-0/addInterval 2 GeV 4 GeV
#/vis/filtering/trajectories/attributeFilter-0/addInterval 3 eV 3.1 eV
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add neutron
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add opticalphoton

#acc. to ApplicationDeveloperHandbook red = x-axis; green = y-axis; blue = z-axis
#/vis/scene/add/axes 0 0 0 1 cm
#vis/scene/add/trajectories 2
#/vis/scene/add/trajectories rich
/tracking/storeTrajectory 1
/vis/scene/add/trajectories 1
/vis/scene/endOfEventAction accumulate
#/vis/viewer/flush

#===============================================================================
# Set GPS properties

#/gps/particle mu-
#/gps/number 1
#/gps/source/intensity 1.
#/gps/energytype Mono
#/gps/energy 290 GeV
#/gps/pos/centre 0 0 30 m


/gps/particle mu-
/gps/number 1
/gps/source/intensity 1.
/gps/energytype Mono
/gps/energy 4 GeV
/gps/pos/centre  0. 100. 22.5 mm

#/gps/direction 0 -1 0 // this is cos(alpha) !!! 


#/gps/pos/type Volume
#/gps/pos/shape Para
#/gps/pos/centre  0.  100. 22.5 mm #0.245 0 6.  m
#/gps/pos/halfz 22.5 mm
#/gps/pos/halfx 10.5 mm
#/gps/pos/halfy 10.5 mm

# Restrict mu's projection to 0.1-degree cone
#/gps/mintheta 0. deg
#/gps/maxtheta 0.1 deg

###################################################
# Start run


#/run/initialize
/run/beamOn 1
