#include "TCanvas.h"
#include "TTree.h"
#include "TGaxis.h"
#include "TStyle.h"
#include "TFile.h"
#include <iostream>
#include "TMath.h"
#include "TChain.h"
#include "/media/ryan/Storage/computing/beamRadSim/include/brROOTEvent.hh"
#include "TGraph.h"
#include "TVector.h"
#include "TVectorF.h"
#include "TH1.h"
#include "TH1F.h"
#include "TString.h"
#include "TChain.h"
using namespace std;


void gammaEDepElectronCount(TString ene){

//retreive file

  TChain rootEvents("Events");
  TString fileDir = "/media/ryan/Storage/computing/beamRadSim/data/";
  TString xTitle = "Number of Gamma-Generated Electrons";
  rootEvents.Add(fileDir+ene+".root");
  std::cout << "Reading file..." << std::endl;
  brROOTEvent* myROOTEvent = new brROOTEvent();
  rootEvents.SetBranchAddress("ROOTEvent", &myROOTEvent);
  Long64_t nentries=rootEvents.GetEntries();

//initialize variables
  double EDep=0;
  double h=4.135668*pow(10,-15);
  double c=3*pow(10,8);
  int eCount=0;
  vector<int> muonHits;
  int count = 0;

TFile *out = new TFile(fileDir+"GammaECount"+ene+".root","RECREATE");
  TH1I* hEneDeposit = new TH1I("hEneDeposit","",1000,1,50001);

//get data in file
  for (Long64_t i=0;i<nentries;i++) {
	//my issue may have to do with this
	rootEvents.GetEntry(i);
	EDep = myROOTEvent->GetEventEnergyDeposit();
	eCount = std::floor(EDep*1000000/10); //convert MeV to eV, then divide by 10 eV per electron-hole pair, then set to integer
	hEneDeposit->Fill(eCount);
  }



for (int j=0; j<muonHits.size(); j++){
	if(muonHits[j]>0) hEneDeposit->Fill(muonHits[j]);
}

hEneDeposit->SetLineColor(kBlue);
hEneDeposit->GetXaxis()->SetTitle(xTitle);
hEneDeposit->GetYaxis()->SetTitle("Bin Members");
hEneDeposit->SetTitle("Electron-Hole Pairs Generated by Incident X-Rays, " + ene);

  TCanvas *c1 = new TCanvas("c1","c1",0,400,600,300);  
  hEneDeposit->Draw();
  out->Write();
}
